### ISSUE TITLE
Register button does not work on production (or testing)

### ISSUE THREAD

**Issue by ARMmaster17** [CS4850Group5A/VirtuDoc#132]
https://github.com/CS4850Group5A/VirtuDoc/blob/74f2f5d76b031be9ec7cdedc3dd121576be12d7c/src/main/resources/templates/login.html#L158

# Implementation
- [x]  Change button to use relative links (preferably as a `<a>` tag or another method that doesn't use JS).
- [x] Add E2E test that visits registration page.

**Comment by mo-umar** [comment]
The button works now both on local host and when you visit virtudoc.herokuapp.com
