### ISSUE TITLE
Authentication Glue

### ISSUE THREAD

**Issue by ARMmaster17** [CS4850Group5A/VirtuDoc#37]
Now that the backend (#25) and the frontend (#32) are done, they now need to be glued together. #25 has a link to a PR on another Java Spring project that shows how the two need to be glued together.

- [x] Add new attributes to `UserAccount` entity model.
- [x] Set the login button to POST the `username` and `password` fields to `/authenticate` (controller for this route is already implemented internally by Spring Security).
- [x] Create a controller route for POST `/registration` that uses the `AuthenticationService` to create a new user account.
- [x] Add `/login` and `/registration` to `SecurityConfiguration.configure()` as routes that do not need authentication.
- [x] (OPTIONAL) Create a DTO user object to send to the Thymeleaf form instead of the `UserAccount` object, which will protect against parameter injection attacks.

Out of scope, but the next logical step would be to send a confirmation email to new users. Should probably be done in another ticket.

**Comment by mo-umar** [comment]
All of the tasks in this issue are completed.
